### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by metamopqoz** [sergree/gilly#1]
When i want to run a script,this throws an error.
![Screenshot_4](https://user-images.githubusercontent.com/61648857/99878542-3d585080-2c17-11eb-9e70-75804e92a9e5.png)

**Comment by sergree** [comment]
Hello!

Try to run:
`pip install discord.py vk` on Windows.
or 
`python3 -m pip install discord.py vk` if you use linux.

**Comment by metamopqoz** [comment]
Many errors when i use 'pip install discord.py vk' on Windows.

**Comment by metamopqoz** [comment]
![1224](https://user-images.githubusercontent.com/61648857/99879044-d0df5080-2c1a-11eb-8528-028f27fd9392.png)

**Comment by sergree** [comment]
The solution is in your screenshot
![img](https://user-images.githubusercontent.com/43672811/99879303-274d8e80-2c1d-11eb-9602-10add0f008e8.png)
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by sergree** [comment]
If no luck, try to use Python 3.8, not Python 3.9

**Comment by metamopqoz** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/61648857/99880277-929a5f00-2c23-11eb-80e1-c3f585ce6776.png)
((((

**Comment by metamopqoz** [comment]
This happens when I try to run the gil.py script

**Comment by metamopqoz** [comment]
![343434](https://user-images.githubusercontent.com/61648857/99880339-dbeaae80-2c23-11eb-8559-f39ed49c4d7c.png)

**Comment by sergree** [comment]
i think your config structure is broken. missing `]` or `,`, or smthing like that

**Comment by 2006lev-Web** [comment]
![Screenshot_2021-07-22-18-46-42-969_mobileSSH feng gao](https://user-images.githubusercontent.com/64630503/126669644-2bae6e89-e287-43df-9b36-c0af4159f5f0.jpg)
Не работает

**Comment by sergree** [comment]
> ![Screenshot_2021-07-22-18-46-42-969_mobileSSH feng gao](https://user-images.githubusercontent.com/64630503/126669644-2bae6e89-e287-43df-9b36-c0af4159f5f0.jpg)
> Не работает

Похоже запускаете на 2-м питоне, а нужно на 3-м
 `python3 gil.py `

**Comment by 2006lev-Web** [comment]
![IMG_20210722_203109](https://user-images.githubusercontent.com/64630503/126683095-7b6d073f-b07e-4116-bb03-05eb714ed3aa.jpg)
Что это значит

**Comment by sergree** [comment]
Что-то новое, не знаю.. в `config.py` все ок?

**Comment by 2006lev-Web** [comment]
![IMG_20210722_224819](https://user-images.githubusercontent.com/64630503/126700720-a34ad2fb-f38e-4806-af40-9b89e40e6c95.jpg)
Хз я только менял discord_to_discord_channel_id is чата и токи вк и дс

**Comment by sergree** [comment]
Хз) у меня норм работает на питоне 3.6 и последней discord.py

**Comment by V8275** [comment]
У меня выдаёт такую ошибку 'NoneType' object has no attribute 'send'. С чем это может быть связано и как починить? Все поля в config.py заполнены

**Comment by sergree** [comment]
> 
> 
> У меня выдаёт такую ошибку 'NoneType' object has no attribute 'send'. С чем это может быть связано и как починить? Все поля в config.py заполнены

Похоже бот не видит один из каналов здесь:
`discord_channel_ids`
https://github.com/sergree/gilly/blob/master/config.py#L36-L38

Или здесь:
`discord_to_discord_channel_id`
https://github.com/sergree/gilly/blob/master/config.py#L51

Либо указан неверный ID канала, либо нету прав на чтение и отправку в канал.
Но я не уверен. 😀

**Comment by V8275** [comment]
> Либо указан неверный ID канала, либо нету прав на чтение и отправку в канал.

Почему не может быть прав на чтение и отправку? Как предоставить доступ?

**Comment by sergree** [comment]
> > Либо указан неверный ID канала, либо нету прав на чтение и отправку в канал.
> 
> Почему не может быть прав на чтение и отправку? Как предоставить доступ?

Может у бота нет нужной роли в Discord, и он не видит канал. То есть можно попробовать дать ему нужную роль или настроить канал как-то в Discord

**Comment by V8275** [comment]
Попробовал - не получается. Может Вконтакте тоже надо предоставить доступ, но там я тоже не очень понимаю как

**Comment by sergree** [comment]
> Попробовал - не получается. Может Вконтакте тоже надо предоставить доступ, но там я тоже не очень понимаю как

Не знаю как помочь :( попробуйте другого бота, например https://github.com/MrZillaGold/VK2Discord

**Comment by V8275** [comment]
Спасибо, попробую)
